services:
  api:
    image: tandem-api
    build:
      context: backend

      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/src
    #env_file:
    #  - .env
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/tandem
  # test:
  #   command: node src/tests.js
  #   image: tandem-api
  #   build: .
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./src/tests.js:/app/src/tests.js
  frontend:

    image: lingolink-frontend

    build:

      context: frontend

      dockerfile: Dockerfile

    ports:

      - 5173:5173

    volumes:

      - ./frontend/src:/app/src

      - ./frontend/public:/app/public
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
